name = "flight_deck"
description = ""
version = "0.1.0-dev"

authors = ["Carl Klein"]
maintainers = ["Carl Klein <carlj.klein@gmail.com>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["flight_deck"]
